imgs_training: /home/sepal-user/data_ssl4eo/data_ssl4eo/training/imgs
labels_training: /home/sepal-user/sig-ssl4eo/fao_models/data/match_training_sample.csv

imgs_testing: /home/sepal-user/data_ssl4eo/data_ssl4eo/testing/imgs
labels_testing: /home/sepal-user/sig-ssl4eo/fao_models/data/match_testing_sample.csv

model_root: /home/sepal-user/sig-ssl4eo/B13_vits16_dino_0099_ckpt.pth
model_head_root: null
model_name: linear-dino
resume: false

checkpoints_dir: linear-dino-4
epochs: 15
lr: 0.001
batch_size: 32
num_workers: 16 
random_subset_frac: 0.05

arch: vit_small
avgpool_patchtokens: false
patch_size: 16
n_last_blocks: 4
resume: false
checkpoint_key: teacher
seed: 42
